import { Center, Container, ScrollArea } from "@mantine/core";
import Head from "next/head";
import TableListCoffee from "../components/table_list_coffee";

export default function Home() {

  return (
    <>
      <Head>
        <title>BuyMeCoffee Next Js - 13 </title>
        <meta
          name="description"
          content="Generated by create next app buyme coffee smartcontract"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <TableListCoffee />
        </Container>
      </main>
    </>
  );
}
