import { Center, Container, ScrollArea } from "@mantine/core";
import Head from "next/head";
import Table from "../components/table";

export default function Home() {

  return (
    <>
      <Head>
        <title>BuyMeCoffee Next App</title>
        <meta
          name="description"
          content="Generated by create next app buyme coffee smartcontract"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <ScrollArea>
            <Table />
          </ScrollArea>
        </Container>
      </main>
    </>
  );
}
